---
- name: Ensure required packages are installed
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create media stack directory
  file:
    path: "{{ media_stack_dir }}"
    state: directory
    mode: '0755'

- name: Create all required mount point directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ appdata_dir }}/data"
    - "{{ appdata_dir }}/downloads"
    - "{{ appdata_dir }}/bazarr"
    - "{{ appdata_dir }}/binhex-qbittorrentvpn"
    - "{{ appdata_dir }}/jackett"
    - "{{ appdata_dir }}/jackett/downloads"
    - "{{ appdata_dir }}/overseerr"
    - "{{ appdata_dir }}/Plex-Media-Server"
    - "{{ appdata_dir }}/plex/transcode"
    - "{{ appdata_dir }}/prowlarr"
    - "{{ appdata_dir }}/radarr"
    - "{{ appdata_dir }}/sonarr"

- name: Deploy docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ media_stack_dir }}/docker-compose.yml"
    mode: '0644'

- name: Deploy media stack with docker compose
  shell: docker compose up -d --force-recreate
  args:
    chdir: "{{ media_stack_dir }}"

- name: Display deployment status
  debug:
    msg: "Media stack deployed successfully!"
