---
- name: Disable SELinux permanently
  selinux:
    state: disabled

- name: Disable SELinux for current session
  shell: setenforce 0

- name: Install docker-ce
  package:
    name:
      - docker-ce
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Load iptables kernel modules
  shell: |
    modprobe ip_tables || true
    modprobe iptable_filter || true
    modprobe iptable_nat || true
    modprobe xt_conntrack || true
  changed_when: false

- name: Ensure iptables modules load on boot
  copy:
    content: |
      ip_tables
      iptable_filter
      iptable_nat
      xt_conntrack
    dest: /etc/modules-load.d/iptables.conf
    mode: '0644'

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Open firewall ports for media stack services
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 80/tcp        # HAProxy HTTP
    - 443/tcp       # HAProxy HTTPS
    - 139/tcp       # Samba
    - 445/tcp       # Samba
    - 5055/tcp      # Overseerr
    - 6767/tcp      # Bazarr
    - 7878/tcp      # Radarr
    - 8080/tcp      # qBittorrent
    - 8081/tcp      # Dashboard
    - 8404/tcp      # HAProxy Stats
    - 8989/tcp      # Sonarr
    - 9000/tcp      # Portainer
    - 9117/tcp      # Jackett
    - 9696/tcp      # Prowlarr
    - 32400/tcp     # Plex

- name: Ensure base appdata directory exists
  file:
    path: "{{ appdata_dir }}"
    state: directory
    mode: '0755'

- name: Ensure media directory exists
  file:
    path: "{{ media_dir }}"
    state: directory
    mode: '0755'

- name: Ensure downloads directory exists
  file:
    path: "{{ downloads_dir }}"
    state: directory
    mode: '0755'

- name: Ensure transcode directory exists
  file:
    path: "{{ transcode_dir }}"
    state: directory
    mode: '0755'

- name: Create portainer directory
  file:
    path: "{{ appdata_dir }}/portainer"
    state: directory
    mode: '0755'

- name: Create dashboard directory
  file:
    path: "{{ appdata_dir }}/dashboard"
    state: directory
    mode: '0755'

- name: Deploy dashboard HTML
  template:
    src: index.html.j2
    dest: "{{ appdata_dir }}/dashboard/index.html"
    mode: '0644'

- name: Create haproxy config directory
  file:
    path: "{{ appdata_dir }}/haproxy"
    state: directory
    mode: '0755'

- name: Generate self-signed SSL certificate for HAProxy
  shell: |
    if [ ! -f {{ appdata_dir }}/haproxy/cert.pem ]; then
      openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout {{ appdata_dir }}/haproxy/cert.key \
        -out {{ appdata_dir }}/haproxy/cert.crt \
        -subj "/C=US/ST=State/L=City/O=Media Stack/CN={{ ansible_host }}"
      cat {{ appdata_dir }}/haproxy/cert.crt {{ appdata_dir }}/haproxy/cert.key > {{ appdata_dir }}/haproxy/cert.pem
      chmod 600 {{ appdata_dir }}/haproxy/cert.pem
    fi
  args:
    creates: "{{ appdata_dir }}/haproxy/cert.pem"

- name: Deploy haproxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "{{ appdata_dir }}/haproxy/haproxy.cfg"
    mode: '0644'

- name: Copy docker-compose.yml 
  template:
    src: docker-compose.yml.j2
    dest: "{{ appdata_dir }}/docker-compose.yml"
    mode: '0644'

- name: Deploy media stack 
  shell: docker compose up -d --force-recreate
  args:
    chdir: "{{ appdata_dir }}"

- name: Add hourly cron job to restart qBittorrent container
  cron:
    name: "Restart qBittorrent container"
    minute: "0"
    hour: "*"
    user: root
    job: "cd {{ appdata_dir }} && docker compose restart qbittorrentvpn >> /var/log/qbittorrent-restart.log 2>&1"
    state: present

