version: '3.8'

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - "6767:6767"
    volumes:
      - /mnt/user/appdata/data/:/movies
      - /mnt/user/appdata/data/:/tv
      - /mnt/user/appdata/bazarr:/config
    restart: unless-stopped

  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrentvpn
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
      - "8118:8118"
    volumes:
      - /mnt/user/appdata/downloads:/data
      - /mnt/user/appdata/binhex-qbittorrentvpn:/config
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - "9117:9117"
    volumes:
      - /mnt/user/jacket/:/downloads
      - /mnt/user/appdata/jackett:/config
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - "5055:5055"
    volumes:
      - /mnt/user/appdata/overseerr:/config
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    volumes:
      - /mnt/user/appdata/Plex-Media-Server:/config
      - /mnt/user/plex/transcode:/transcode
      - /mnt/user/appdata/data:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - /mnt/user/appdata/downloads/:/config/qBittorrent/downloads/
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/appdata/data:/movies
      - /mnt/user/appdata/downloads:/downloads
      - /mnt/user/appdata/downloads:/data
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - /mnt/disk1/appdata/data/:/tv
      - /mnt/disk1/appdata/downloads:/downloads
      - /mnt/user/appdata/downloads:/data
      - /mnt/user/appdata/sonarr:/config
    restart: unless-stopped
