version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/appdata/grafana:/var/lib/grafana
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: prom-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - /mnt/user/appdata/alertmanager/storage:/alertmanager
      - /mnt/user/appdata/alertmanager/:/etc/alertmanager/
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /mnt/user/appdata/prometheus/etc:/etc/prometheus/
      - /mnt/user/appdata/prometheus/data:/prometheus/data
    restart: unless-stopped

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: prometheus-blackbox
    ports:
      - "9115:9115"
    restart: unless-stopped
